const $=s=>document.querySelector(s);let mode='live',state='idle',prepared=false,checked=false;
const states={idle:['○','PRIMA DI COMINCIARE','Pronto per la verifica','Prepara il sistema, verifica i segnali e avvia la prova.','In attesa','— / 09:00','—','—','—',0,'Nessuna prova avviata.'],running:['◷','PROVA IN CORSO','Il sistema è sotto osservazione','Registrazione, riproduzione e marcature vengono misurate.','Registrazione e replay','05:12 / 09:00','05:12','50.0','0',58,'05:12 · Replay avviato. Raccolta delle misure in corso.'],done:['✓','PROVA COMPLETATA','Esito positivo','Tutte le verifiche di questa prova sono rientrate nei limiti.','Prova terminata','09:00 / 09:00','09:00','50.0','0',100,'09:00 · Prova completata. Il rapporto è disponibile.'],error:['!','VERIFICA RICHIESTA','Rilevati quadri persi','La prova segnala una discontinuità. Consulta il rapporto.','Prova conclusa con anomalie','09:00 / 09:00','09:00','49.7','12',100,'09:00 · 12 quadri persi in cattura. Soglia richiesta: 0.']};
function render(){document.body.classList.toggle('catalog',mode==='catalog');document.body.dataset.state=state;$('#live-fields').hidden=mode==='catalog';$('#catalog-fields').hidden=mode!=='catalog';$('#config-title').textContent=mode==='live'?'Sorgente e registrazione':'Girato da verificare';$('#check').hidden=mode==='catalog';$('#monitor-label').textContent=mode==='live'?'MONITOR / SDI 1':'MONITOR / FILE SORGENTE';$('.monitor-tag').textContent=mode==='live'?'SDI 1':'FILE';$('#tc-label').textContent=mode==='live'?'TIMECODE / SDI 1':'TIMECODE / SORGENTE';$('#monitor-title').textContent=mode==='live'?'Anteprima segnale':'Anteprima del girato';const d=states[state];['status-icon','status-label','status-title','status-copy','phase','progress-label'].forEach((id,i)=>$('#'+id).textContent=d[i]);if(mode==='catalog')$('#status-copy').textContent=state==='idle'?'Seleziona il girato e avvia la verifica di importazione, proxy ed export.':state==='running'?'Verifica dei fotogrammi del proxy e dell’esportazione in corso.':d[3];if(mode==='catalog'&&state==='running')$('#phase').textContent='Confronto proxy e sorgente';['elapsed','fps','dropped'].forEach((id,i)=>$('#'+id).innerHTML=d[i+6]+'<small>'+['min','q/s','quadri'][i]+'</small>');$('#progress').style.width=d[9]+'%';$('#progress-percent').textContent=d[9]+'%';$('.progress').setAttribute('aria-valuenow',d[9]);$('#remaining').textContent=state==='running'?'Tempo rimanente stimato · 03:48':state==='idle'?'Tempo rimanente —':'Tempo rimanente · 00:00';$('#message').textContent=d[10];$('#tc').textContent=state==='idle'?'--:--:--:--':'00:05:12:24';$('#stop').hidden=state!=='running';['cpu','ram','disk'].forEach((id,i)=>{$('#'+id).textContent=state==='idle'?'—':['32%','3.1 / 8 GB','84 MB/s'][i];$('#'+id+'-bar').style.width=state==='idle'?'0%':[32,39,24][i]+'%'});document.querySelectorAll('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scene===state)));document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('#prepare').disabled=state==='running';$('#check').disabled=!prepared||state==='running';$('#start').disabled=state==='running'||(mode==='live'?!checked:!prepared);$('#action-note').textContent=state==='running'?'Prova simulata. Puoi esplorare gli altri stati in alto.':checked?'Verifica completata. Puoi avviare la prova.':prepared?(mode==='live'?'Sistema preparato. Procedi con Verifica.':'Sistema preparato. Puoi avviare la prova.'):'Prepara il sistema per abilitare la prova.';renderSteps();}
document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{state=b.dataset.scene;render()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;prepared=checked=false;state='idle';render()});$('#prepare').onclick=()=>{prepared=true;render();$('#message').textContent='Preparazione completata · esempio'};$('#check').onclick=()=>{checked=true;render();$('#message').textContent='Segnali, disco e motore verificati · esempio'};$('#start').onclick=()=>{state='running';render()};$('#stop').onclick=()=>{state='idle';render();$('#message').textContent='Prova simulata interrotta.'};
function closeMenus(){document.querySelectorAll('.options').forEach(e=>e.remove());document.querySelectorAll('.pick>button').forEach(b=>b.setAttribute('aria-expanded','false'))}document.querySelectorAll('.pick').forEach(p=>{const trigger=p.querySelector('button');trigger.setAttribute('aria-haspopup','listbox');trigger.setAttribute('aria-label',document.getElementById(p.getAttribute('aria-labelledby')).textContent);trigger.onclick=()=>{const open=trigger.getAttribute('aria-expanded')==='true';closeMenus();if(open)return;trigger.setAttribute('aria-expanded','true');const menu=document.createElement('div');menu.className='options';menu.setAttribute('role','listbox');p.dataset.options.split('|').forEach(value=>{const b=document.createElement('button');b.textContent=value;b.setAttribute('role','option');b.setAttribute('aria-selected',String(trigger.textContent.trim().startsWith(value)));b.onclick=()=>{trigger.innerHTML=value+' <span>⌄</span>';closeMenus();trigger.focus();if(p.id==='codec'){$('#monitor-codec').textContent=value.split(' · ')[0];const num=value.startsWith('HEVC')||value.startsWith('MJPEG');$('#quality').disabled=!num;$('#quality').type=num?'number':'text';$('#quality').value=value.startsWith('HEVC')?150:value.startsWith('MJPEG')?88:'Profilo ProRes';$('#quality-label').textContent=value.startsWith('HEVC')?'Bitrate · Mb/s':'Qualità'}if(p.id==='camera'){const n=parseInt(value);document.querySelectorAll('[data-port]').forEach((b,i)=>{b.classList.toggle('active',i<n);b.querySelector('small').textContent=i<n?'● Segnale':'Non usato'})}};menu.appendChild(b)});menu.onkeydown=e=>{const opts=[...menu.children],i=opts.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();opts[e.key==='Home'?0:e.key==='End'?opts.length-1:(i+(e.key==='ArrowDown'?1:-1)+opts.length)%opts.length].focus()}if(e.key==='Escape'){closeMenus();trigger.focus()}};p.appendChild(menu);menu.firstChild.focus()}});document.addEventListener('click',e=>{if(!e.target.closest('.pick'))closeMenus()});
const dialog=$('#dialog');function show(label,title,body){$('#dialog-label').textContent=label;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;dialog.showModal()}$('#dialog-ok').onclick=()=>dialog.close();$('#folder').onclick=()=>{show('DESTINAZIONE','Cartella del collaudo','<p>Scegli una destinazione di esempio per valutare il selettore.</p><button class="choice">T7 / collaudo</button><button class="choice">Disco di prova / collaudo</button>');dialog.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{$('#folder-name').textContent=b.textContent;dialog.close()})};$('#file').onclick=()=>{show('GIRATO SORGENTE','Seleziona un file','<p>File di esempio per la proposta.</p><button class="choice">Partita · primo tempo.mov</button><button class="choice">Partita · secondo tempo.mov</button>');dialog.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{$('#filename').textContent=b.textContent;dialog.close()})};$('#report').onclick=()=>show('RAPPORTO / '+(mode==='live'?'LIVE':'CATALOG'),'Risultati della prova',state==='idle'?'<p>Non è stata ancora avviata una prova. Seleziona “Esito” o “Anomalia” in alto per vedere un rapporto di esempio.</p>':`<p>Anteprima del rapporto · valori simulati.</p><div class="report-row"><span>Stato</span><b>${state==='running'?'In corso':state==='error'?'Da verificare':'Completata'}</b></div><div class="report-row"><span>Cadenza in uscita</span><b>${state==='error'?'49,7':'50,0'} q/s</b></div><div class="report-row"><span>Quadri persi / limite 0</span><b>${state==='error'?'12 · fuori soglia':'0'}</b></div><div class="report-row"><span>TOP mediano / limite 200 ms</span><b>120 ms</b></div><div class="report-row"><span>Errore leva / limite 2%</span><b>0,4%</b></div>`);$('#log').onclick=()=>show('REGISTRO','Eventi della prova','<p>Esempio di registro, separato dai controlli principali.</p><pre>'+ (state==='idle'?'— Nessuna prova avviata.':'00:00  Preparazione completata\n00:02  Verifica preliminare superata\n00:05  Avvio della prova\n05:12  Raccolta delle misure\n'+(state==='error'?'09:00  ATTENZIONE · 12 quadri persi':state==='done'?'09:00  Prova completata':'05:12  Prova in corso'))+'</pre>');render();
document.querySelectorAll('[data-port]').forEach(b=>b.onclick=()=>{if(!b.classList.contains('active'))return;const s='SDI '+b.dataset.port;$('#monitor-label').textContent='MONITOR / '+s;$('.monitor-tag').textContent=s;$('#tc-label').textContent='TIMECODE / '+s});

// Stati illustrativi della proposta: in produzione servirà l’esito reale di ogni fase.
function renderSteps(){
 $('#running-banner').hidden=state!=='running';
 $('#running-phase').textContent=mode==='live'?'Fase 04 / 08 · Registrazione':'Fase 03 / 06 · Confronto proxy e sorgente';
 $('#running-percent').textContent=states.running[9]+'%';

 const names=mode==='live'?['Sistema','Preparazione del banco','Segnale SDI','Registrazione','Operazioni di replay','Verifica delle misure','Arresto del banco','Rapporto']:['Preparazione del banco','Importazione del girato','Confronto proxy e sorgente','Esportazione','Verifica delle protezioni','Rapporto'];
 const active=mode==='live'?3:2;
 const statuses=names.map((_,i)=>state==='idle'?'waiting':state==='done'?'passed':state==='error'?(i===active?'failed':'passed'):(i<active?'passed':i===active?'running':'waiting'));
 const labels={waiting:'In attesa',passed:'Superata',running:'In corso',failed:'Problema'};
 $('#steps-list').innerHTML=names.map((name,i)=>`<li class="step ${statuses[i]}"><span class="step-dot" aria-hidden="true">${statuses[i]==='passed'?'✓':statuses[i]==='failed'?'!':''}</span><div><strong>${name}</strong><span>${labels[statuses[i]]}</span></div><span class="step-number">${String(i+1).padStart(2,'0')}</span></li>`).join('');
 const passed=statuses.filter(x=>x==='passed').length;
 $('#steps-summary').textContent=state==='idle'?names.length+' fasi previste':passed+' / '+names.length+' superate'+(state==='error'?' · 1 problema':state==='running'?' · 1 in corso':'');
 if(state==='error'&&mode==='catalog'){$('#status-title').textContent='Problema nel confronto del proxy';$('#status-copy').textContent='La verifica ha rilevato una differenza tra proxy e sorgente.';}
}
